package com.aoaojiao.rpc.metrics;

/**
 * Prometheus 指标导出器
 * 生成 Prometheus 文本格式的指标输出
 * 应用需要自行暴露 /metrics 端点
 */
public class PrometheusExporter {

    private final MetricsRegistry registry;

    public PrometheusExporter(MetricsRegistry registry) {
        this.registry = registry;
    }

    /**
     * 获取 Prometheus 格式的指标输出
     */
    public String collect() {
        StringBuilder sb = new StringBuilder();

        // 输出计数器
        for (String name : registry.getCounterNames()) {
            String sanitizedName = sanitizeName(name);
            sb.append("# TYPE ").append(sanitizedName).append(" counter\n");
            sb.append(sanitizedName).append(" ").append(registry.counter(name)).append("\n");
        }

        // 输出 Histogram
        for (String name : registry.getHistogramNames()) {
            String sanitizedName = sanitizeName(name);
            MetricsRegistry.Histogram histogram = registry.getHistogram(name);
            MetricsRegistry.HistogramSnapshot snapshot = histogram.getSnapshot();

            sb.append("# TYPE ").append(sanitizedName).append(" histogram\n");
            sb.append(sanitizedName).append("_count ").append(histogram.getCount()).append("\n");
            sb.append(sanitizedName).append("_sum ").append(snapshot.getSum()).append("\n");
            sb.append(sanitizedName).append("_mean ").append(snapshot.getMean()).append("\n");
            sb.append(sanitizedName).append("_p50 ").append(snapshot.getMedian()).append("\n");
            sb.append(sanitizedName).append("_p90 ").append(snapshot.get90thPercentile()).append("\n");
            sb.append(sanitizedName).append("_p99 ").append(snapshot.get99thPercentile()).append("\n");
            sb.append(sanitizedName).append("_p999 ").append(snapshot.get999thPercentile()).append("\n");
        }

        // 输出 Gauge
        for (String name : registry.getGaugeNames()) {
            String sanitizedName = sanitizeName(name);
            sb.append("# TYPE ").append(sanitizedName).append(" gauge\n");
            sb.append(sanitizedName).append(" ").append(registry.gauge(name)).append("\n");
        }

        return sb.toString();
    }

    /**
     * 获取 Prometheus 格式的指标输出（带帮助信息）
     */
    public String collectWithHelp() {
        StringBuilder sb = new StringBuilder();
        sb.append("# RPC Metrics\n");
        sb.append("# Generated by aoaojiao-rpc\n\n");

        // 输出计数器
        sb.append("# === Counters ===\n");
        for (String name : registry.getCounterNames()) {
            String sanitizedName = sanitizeName(name);
            sb.append("# HELP ").append(sanitizedName).append(" Counter metric\n");
            sb.append("# TYPE ").append(sanitizedName).append(" counter\n");
            sb.append(sanitizedName).append(" ").append(registry.counter(name)).append("\n");
        }
        sb.append("\n");

        // 输出 Histogram
        sb.append("# === Histograms ===\n");
        for (String name : registry.getHistogramNames()) {
            String sanitizedName = sanitizeName(name);
            MetricsRegistry.Histogram histogram = registry.getHistogram(name);
            MetricsRegistry.HistogramSnapshot snapshot = histogram.getSnapshot();

            sb.append("# HELP ").append(sanitizedName).append(" Histogram metric\n");
            sb.append("# TYPE ").append(sanitizedName).append(" histogram\n");
            sb.append(sanitizedName).append("_count ").append(histogram.getCount()).append("\n");
            sb.append(sanitizedName).append("_sum ").append(snapshot.getSum()).append("\n");
            sb.append(sanitizedName).append("_mean ").append(snapshot.getMean()).append("\n");
            sb.append(sanitizedName).append("_p50 ").append(snapshot.getMedian()).append("\n");
            sb.append(sanitizedName).append("_p90 ").append(snapshot.get90thPercentile()).append("\n");
            sb.append(sanitizedName).append("_p99 ").append(snapshot.get99thPercentile()).append("\n");
            sb.append(sanitizedName).append("_p999 ").append(snapshot.get999thPercentile()).append("\n");
        }
        sb.append("\n");

        // 输出 Gauge
        sb.append("# === Gauges ===\n");
        for (String name : registry.getGaugeNames()) {
            String sanitizedName = sanitizeName(name);
            sb.append("# HELP ").append(sanitizedName).append(" Gauge metric\n");
            sb.append("# TYPE ").append(sanitizedName).append(" gauge\n");
            sb.append(sanitizedName).append(" ").append(registry.gauge(name)).append("\n");
        }

        return sb.toString();
    }

    /**
     * 获取简单统计摘要
     */
    public String summary() {
        return String.format(
            "RPC Metrics Summary: counters=%d, histograms=%d, gauges=%d",
            registry.getCounterNames().size(),
            registry.getHistogramNames().size(),
            registry.getGaugeNames().size()
        );
    }

    /**
     * 清理指标名中的非法字符
     */
    private String sanitizeName(String name) {
        return name.replace('.', '_')
                   .replace('-', '_')
                   .replace(' ', '_')
                   .replaceAll("[^a-zA-Z0-9_]", "");
    }
}